package de.verdox.mccreativelab;

import de.verdox.mccreativelab.blockbreak.BlockBreakSpeedModifier;
import de.verdox.mccreativelab.event.MCCreativeLabReloadEvent;
import de.verdox.mccreativelab.generator.AssetPath;
import de.verdox.mccreativelab.generator.ResourcePackFileHoster;
import de.verdox.mccreativelab.generator.listener.ResourcePackListener;
import de.verdox.mccreativelab.generator.resourcepack.CustomResourcePack;
import de.verdox.mccreativelab.generator.resourcepack.renderer.HudRendererImpl;
import de.verdox.mccreativelab.generator.resourcepack.renderer.element.HudRenderer;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.RecipeChoice;
import org.bukkit.inventory.ShapelessRecipe;
import org.bukkit.plugin.java.JavaPlugin;

public class MCCreativeLabExtension extends JavaPlugin {
    private static MCCreativeLabExtension INSTANCE;
    public static MCCreativeLabExtension getInstance() {
        return INSTANCE;
    }
    private final ResourcePackFileHoster resourcePackFileHoster = new ResourcePackFileHoster("127.0.0.1", 8080);
    private final CustomResourcePack customResourcePack = new CustomResourcePack("MCCreativeLab", 18, "Generated by MCCreativeLab", AssetPath.buildPath("resourcePacks"));
    private final HudRendererImpl hudRenderer = new HudRendererImpl();

    @Override
    public void onLoad() {
        INSTANCE = this;
    }

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(new ResourcePackListener(), this);
        Bukkit.getPluginManager().registerEvents(new BlockBreakSpeedModifier(), this);
        this.hudRenderer.start();
    }

    @Override
    public void onDisable() {
        try {
            resourcePackFileHoster.closeAndWait();
            this.hudRenderer.interrupt();
            this.hudRenderer.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    public void reloadPlugin(){
        Bukkit.getPluginManager().callEvent(new MCCreativeLabReloadEvent());
    }

    public ResourcePackFileHoster getResourcePackFileHoster() {
        return resourcePackFileHoster;
    }

    public CustomResourcePack getCustomResourcePack() {
        return customResourcePack;
    }

    public HudRenderer getHudRenderer() {
        return hudRenderer;
    }
}
